echo/echo/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include

from apps.core import debug
from apps.core.debug import test
from apps.core.views import profils, rdvs, accueil, patients, parametres_compte, praticiens, admissions, \
    ordonnances, traitements, prescriptions, certificats, prestations, etablissements, utils, reglements, grossesses, \
    consultations, analyses_biologiques, listes_choix, templates_edition, rapports,motifs, absence, mutuelle


from django.conf import settings

from apps.core.views.consultations import base, gynecologique, obstetrique, images, pma
from apps.core.views.devices import worklists, devices

urlpatterns = [
    # Toolbar
    path('__debug__/', include(debug_toolbar.urls)),

    # Admin
    re_path(r'^admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),

    re_path(r'^', include('apps.chat.urls')),

    # Authentification
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login_v2.html'), name='login'),
    path('accounts/password_reset/', auth_views.LoginView.as_view(template_name='core/login.html'),
         name='password_reset'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='core/login.html')),

    # Module tableau de bord
    path('accueil/', accueil.Accueil.as_view(), name='accueil-1'),
    path('', accueil.Accueil.as_view(), name='accueil'),

    # Module utilisateurs/profils
    path('utilisateurs/', profils.ProfilList.as_view(), name='profils_list'),
    path('utilisateurs/ajouter', profils.ProfilCreate.as_view(), name='profil_form'),
    path('utilisateurs/<int:pk>/modifier/', profils.ProfilUpdate.as_view(), name='profil_modifier'),
    path('utilisateurs/<int:pk>/supprimer', profils.supprimer_profil, name='profil_supprimer'),
    path('utilisateurs/<int:pk>/mdp/', profils.MotDePasseUpdate.as_view(), name='profil_modifier_mdp'),

    # Module paramètres
    path('parametres/<int:pk>', parametres_compte.ParametresGeneraux.as_view(), name='parametres_generaux'),

    # Module rendez-vous
    path('rdvs/', rdvs.RdvList.as_view(), name='rdvs_list'),
    re_path(r'rdvs/ajouter/$', rdvs.RdvCreate.as_view(), name='rdv_form'),
    path('rdvs/<int:pk>/modifier/', rdvs.RdvUpdate.as_view(), name='rdv_modifier'),
    path('rdvs/<int:pk>/modifier_horaire/', rdvs.modifier_horaire, name='rdv_modifier_horaire'),
    path('rdvs/<int:pk>/supprimer/', rdvs.supprimer_rdv, name='rdv_supprimer'),
    path('rdvs/<int:pk>/rappel/', rdvs.rappel_rdv, name='rdv_rappel'),
    re_path(r'rdvs/dispo/ajouter/$', rdvs.RdvDispoCreate.as_view(), name='rdv_dispo'),
    path('absence/ajouter/', absence.AbsenceCreate.as_view(), name='absence_form'),
    path('absences/<int:pk>/modifier/', absence.AbsenceUpdate.as_view(), name='absence_modifier'),
    path('programme_operatoire/ajouter/', absence.ProgrammeOperatoireCreate.as_view(), name='programme_operatoire_form'),
    path('programme_operatoire/<int:pk>/modifier/', absence.ProgrammeOperatoireUpdate.as_view(), name='programme_operatoire_modifier'),
    # Module patients
    path('patients/', patients.PatientList.as_view(), name='patients_list'),
    re_path(r'patients/recherche/$', patients.PatientList.as_view(), name='patients_list1'),
    re_path(r'patients/recherche_async/$', patients.rechercher_patient, name='patients_list2'),
    #path('patients/recherche/', patients.rechercher_patient, name='patients_recherche'),
    path('patients/<int:pk>/admission/', patients.admission_patient, name='patient_admission'),
    path('patients/<int:pk>/admissions/', patients.liste_admissions_patient, name='patient_admissions_list'),
    path('patients/<int:pk>/fichiers/', patients.fichiers_list, name='patient_fichiers_list'),
    path('patients/<int:pk>/telecharger/', patients.fichiers_telecharger, name='patient_fichiers_telecharger'),
    path('patients/ajouter/', patients.PatientCreate.as_view(), name='patient_form'),
    path('patients/<int:pk>/modifier', patients.PatientUpdate.as_view(), name='patient_modifier'),
    path('patients/<int:pk>/', patients.PatientView.as_view(), name='patient_afficher'),
    path('patients/<int:pk>/infos/', patients.infos_patient, name='patient_infos'),
    path('patients/<int:pk>/supprimer', patients.supprimer_patient, name='patient_supprimer'),
    path('patients/<int:pk>/antecedents', patients.enregistrer_antecedents, name='patient_enregistrer_antecedents'),
    path('patients/<int:pk>/antecedents/ajouter', patients.ajouter_antecedent, name='patient_ajouter_antecedent'),
    path('antecedent/<int:pk>/supprimer/', patients.supprimer_antecedent, name='patient_supprimer_antecedent'),
    path('patients/<int:pk>/notes', patients.enregistrer_notes, name='patient_enregistrer_notes'),
    path('patients/<int:pk>/consultation/ajouter/', consultations.base.ConsultationCreate.as_view(),
         name='consultation_form'),
    path('patients/<int:patient_pk>/consultations/', consultations.base.ConsultationList.as_view(),
         name='consultation_form'),
    path('patients/<int:pk>/consultation/enregistrer/', base.enregistrer_consultation, name='consultation_enregistrer'),
    path('patients/<int:pk>/consultation/terminer/', base.terminer_consultation, name='consultation_terminer'),
    path('patients/<int:patient_pk>/consultation/<int:pk>/modifier/', base.ConsultationUpdate.as_view(),
         name='consultation_modifier'),
    path('patients/<int:pk>/praticien/ajouter/', patients.ajouter_praticien, name='patient_praticien_ajouter'),
    path('patients/<int:pk>/fichier/ajouter/', patients.ajouter_fichier, name='patient_fichier_ajouter'),
    path('patients/<int:pk>/fichier/<int:fichier_pk>/deplacer/', patients.deplacer_fichier,
         name='patient_fichier_daplacer'),
    path('patients/<int:pk>/fichier/<int:fichier_pk>/supprimer/', patients.supprimer_fichier,
         name='patient_fichier_supprimer'),
    path('patients/<int:pk>/mot_cle/ajouter/', patients.ajouter_mot_cle, name='patient_mot_cle_ajouter'),
    path('patients/<int:pk>/mot_cle/supprimer/', patients.supprimer_mot_cle, name='patient_mot_cle_supprimer'),
    path('patients/<int:pk>/antecedent_obstetrique/ajouter/', patients.AntecedentObstetriqueCreate.as_view(), name='patient_antecedent_obstetrique_ajouter'),
    path('antecedent_obstetrique/<int:pk>/modifier', patients.AntecedentObstetriqueUpdate.as_view(), name='patient_antecedent_obstetrique_modifier'),
    path('antecedent_obstetrique/<int:pk>/supprimer/', patients.supprimer_antecedent_obstetrique, name='patient_antecedent_obstetrique_supprimer'),
    path('patients/<int:pk>/grossesse/ajouter', grossesses.GrossesseCreate.as_view(), name='patient_grossesse_ajouter'),
    path('grossesse/<int:pk>/modifier', grossesses.GrossesseUpdate.as_view(), name='patient_grossesse_modifier'),
    path('patients/<int:pk>/mesures/ajouter', patients.MesuresPatientCreate.as_view(), name='patient_mesures_ajouter'),
    path('mesures/<int:pk>/modifier', patients.MesuresPatientUpdate.as_view(), name='patient_mesures_modifier'),
    path('grossesses/<int:pk>/calendrier', grossesses.CalendrierGrossesseDetail.as_view(), name='grossesse_calendrier'),
    path('grossesses/<int:pk>/mesures/', grossesses.mesures, name='grossesse_mesures'),
    path('patients/<int:pk>/alerte/', patients.ajouter_alerte, name='patient_alerte_ajouter'),
    path('alertes/<int:pk>/supprimer/', patients.supprimer_alerte, name='patient_alerte_supprimer'),
    path('patient/<int:pk>/consultation/rechercher/', patients.rechercher_consultation, name='patient_consultation_rechercher'),

    # Analyses biologiques
    path('patients/<int:pk>/analyses/ajouter/', analyses_biologiques.PrescriptionCreate.as_view(), name='patient_analyses_ajouter'),
    path('patients/<int:pk>/analyses/', analyses_biologiques.prescriptions, name='patient_analyses_liste'),
    path('analyses/<int:pk>/modifier/', analyses_biologiques.PrescriptionUpdate.as_view(), name='patient_analyses_modifier'),
    path('analyses/<int:pk>/supprimer/', analyses_biologiques.supprimer_prescription, name='patient_analyses_supprimer'),
    path('analyses/enregistrer/', analyses_biologiques.enregistrer_prescription, name='patient_analyses_enregistrer'),
    path('analyses-biologiques/', analyses_biologiques.AnalyseBiologiqueList.as_view(), name='analyses_biologiques_liste'),
    path('analyses-biologiques/ajouter/', analyses_biologiques.AnalyseBiologiqueCreate.as_view(), name='analyses_biologiques_form'),
    path('analyses-biologiques/<int:pk>/modifier', analyses_biologiques.AnalyseBiologiqueUpdate.as_view(), name='analyses_biologiques_modifier'),
    path('analyses-biologiques/<int:pk>/supprimer', analyses_biologiques.supprimer_analyse_biologique, name='analyses_biologiques_supprimer'),
    path('analyses-biologiques/recherche/', analyses_biologiques.rechercher_analyse, name='analyses_biologiques_recherche'),
    path('collection-analyses/', analyses_biologiques.CollectionAnalyseBiologiqueList.as_view(), name='collection_analyses_liste'),
    path('collection-analyses/ajouter/', analyses_biologiques.CollectionAnalyseBiologiqueCreate.as_view(), name='collection_analyses_form'),
    path('collection-analyses/<int:pk>/modifier', analyses_biologiques.CollectionAnalyseBiologiqueUpdate.as_view(), name='collection_analyses_modifier'),
    path('collection-analyses/<int:pk>/supprimer', analyses_biologiques.supprimer_collection_analyse_biologique, name='collection_analyses_supprimer'),
    path('collection-analyses/recherche/', analyses_biologiques.rechercher_collection, name='collection_analyses_recherche'),
    path('resultats-analyses', analyses_biologiques.ajouter_resultats_analyses, name='resultats_analyses_ajouter'),

echo/apps/chat/models.py
# -*- coding: utf-8 -*-

from django.db import models
from model_utils.models import TimeStampedModel, SoftDeletableModel
from django.conf import settings
from django.template.defaultfilters import date as dj_date
from django.utils.translation import gettext as _
from django.utils.timezone import localtime

from apps.core.models import Profil


class Dialog(TimeStampedModel):
    owner = models.ForeignKey(Profil, verbose_name=_("Dialog owner"), related_name="selfDialogs",
                              on_delete=models.CASCADE)
    opponent = models.ForeignKey(Profil, verbose_name=_("Dialog opponent"), on_delete=models.CASCADE)

    def __str__(self):
        return _("Discussion avec ") + self.opponent.nom


class Message(TimeStampedModel, SoftDeletableModel):
    dialog = models.ForeignKey(Dialog, verbose_name=_("Dialog"), related_name="messages", on_delete=models.CASCADE)
    sender = models.ForeignKey(Profil, verbose_name=_("Author"), related_name="messages",
                               on_delete=models.CASCADE)
    text = models.TextField(verbose_name=_("Message text"))
    read = models.BooleanField(verbose_name=_("Read"), default=False)
    all_objects = models.Manager()

    def get_formatted_create_datetime(self):
        return dj_date(self.created, settings.DATETIME_FORMAT)

    def __str__(self):
        return self.sender.nom + "(" + self.get_formatted_create_datetime() + ") - '" + self.text + "'"

echo/apps/core/views/accueil.py
import json
import os
from datetime import date, datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.db.models import Q, F
from django.views.generic import TemplateView
from django.core import serializers

from apps.core.models import Rdv, Patient, Consultation, MotifConsultation, Admission, Medecin
from apps.core.serializers import AdmissionSerializer, ConsultationSerializer, RdvSerializer, MedecinSerializer, \
    MotifRdv, MotifRdvSerializer


# Reinitialise l'ordre de passage des patients de la journée
# Todo transférer comme signal ou dans le module patients
def reinitialiser_ordre_passage(request):
    today = date.today()
    admissions = Admission.objects.filter(date__day=today.day, date__month=today.month, date__year=today.year,
                                          statut='1',
                                          patient__compte=request.user.profil.compte).order_by('ordre')
    count = 1
    for adm in admissions:
        # print('Admission {} ordre {}'.format(adm.patient, adm.ordre))
        adm.ordre = count
        adm.save()
        count = count + 1


class Accueil(PermissionRequiredMixin, TemplateView):
    template_name = 'core/accueil_v2.html'
    permission_required = 'core.view_rdv'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        compte = self.request.user.profil.compte.raison_sociale.replace(' ', '+')
        os.system(f'echo "export EE_COMPTE={compte}" >> ~/.bashrc')

        reinitialiser_ordre_passage(self.request)

        if 'msg' in self.request.GET:
            if self.request.GET['msg'] == 'admission_succes':
                context['msg'] = 'Patient admis avec succès'
            if self.request.GET['msg'] == 'consultation_terminee_succes':
                context['msg'] = 'Consultation terminée avec succès'
            if self.request.GET['msg'] == 'consultation_demarree_succes':
                context['msg'] = 'Consultation démarrée avec succès'

        today = date.today()

        if 'date' in self.request.GET:
            today = self.request.GET['date']

        context['date'] = today

        now = datetime.now()
        periode_debut = now - timedelta(days=10)
        periode_debut = periode_debut.replace(hour=0, minute=0)
        periode_fin = now + timedelta(days=10)
        periode_fin = periode_fin.replace(hour=23, minute=59)
        jour_min = now.replace(hour=0, minute=0)
        jour_max = now.replace(hour=23, minute=59)

        # rdvs = Rdv.objects.filter(Q(compte=self.request.user.profil.compte) &
        #                          (Q(debut__day=today.day) & Q(debut__month=today.month) & Q(debut__year=today.year))
        #                          | (Q(ancien_debut__day=today.day) & Q(ancien_debut__month=today.month) & Q(ancien_debut__year=today.year)))

        # Chercher tous les rdv dont la date de debut ou l'anicenne date de début est dans [aujourd'hui-10, aujourd'hui+10]
        rdvs = Rdv.objects.filter(Q(compte=self.request.user.profil.compte) &
                                  (Q(debut__gte=periode_debut) & Q(debut__lte=periode_fin)
                                   | (Q(ancien_debut__gte=periode_debut) & Q(
                                              ancien_debut__lte=periode_fin))))\
                                    .select_related('patient').select_related('praticien')

        """
        rdvs_json = serializers.serialize('json', list(rdvs), use_natural_foreign_keys=True,
                                          fields=(
                                              'id', 'debut', 'ancien_debut', 'nom', 'nom_naissance', 'prenom', 'telephone', 'ville',
                                              'praticien', 'statut', 'motif', 'nouveau', 'patient', 'patient_rappele'))
                                              """
        rdvs_json = RdvSerializer(rdvs, many=True)
        context['rdvs_json'] = json.dumps(rdvs_json.data)

        admissions = Admission.objects.filter(date__gte=jour_min,
                                              date__lte=jour_max,
                                              patient__compte=self.request.user.profil.compte) \
                                        .order_by('ordre') \
                                        .select_related('patient').select_related('patient__adresse')
        admissions_json = AdmissionSerializer(admissions, many=True)
        context['admissions_json'] = json.dumps(admissions_json.data)

        consultations = Consultation.objects.filter(patient__compte=self.request.user.profil.compte,
                                                    date__gte=periode_debut, date__lte=periode_fin)
        consultations_json = ConsultationSerializer(consultations, many=True)
        context['consultations_json'] = json.dumps(consultations_json.data)

        motifs_consultation = MotifConsultation.objects.all()
        motifs_consultation_json = serializers.serialize('json', list(motifs_consultation),
                                                         use_natural_foreign_keys=True)
        context['motifs_consultation_json'] = motifs_consultation_json

        praticiens = Medecin.objects.filter(compte=self.request.user.profil.compte)
        context['praticiens'] = praticiens
        context['praticiens_json'] = json.dumps(MedecinSerializer(praticiens, many=True).data)

        motifs_rdvs = MotifRdv.objects.all()
        context['motifs_rdv'] = motifs_rdvs
        context['motifs_rdv_json'] = json.dumps(MotifRdvSerializer(motifs_rdvs, many=True).data)

        return context

echo/templates/core/etablissement_form.html
{% extends "base_dialog.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="p-4">
        <form id="form_1" class="form" method="post" action="">
            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                <div class="form-group col-5">
                    <label>Nom</label>
                    {% render_field form.nom class+="form-control form-control-sm" %}
                    <div class="invalid-feedback"
                         {% if form.nom.errors %}style="display: block"{% endif %}>
                        {{ form.nom.errors }}
                    </div>
                </div>
                <div class="form-group col-4">
                    <label>Téléphone</label>
                    {% render_field form.telephone class+="form-control form-control-sm" %}
                    <div class="invalid-feedback"
                         {% if form.telephone.errors %}style="display: block"{% endif %}>
                        {{ form.telephone.errors }}
                    </div>
                </div>

            </div>

            <div class="d-flex mt-4 justify-content-end">
                <a href="/etablissements/" class="btn btn-default">Annuler</a>
                <button type="submit" id="btn_enregistrer" class="ml-2 btn btn-primary font-weight-bolder"
                        onclick="this.disabled=true,this.form.submit();">
                    <i class="ki ki-check icon-sm"></i>
                    Enregistrer
                </button>
            </div>

        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script type="text/javascript">

    </script>
    <script src="{% static "js/core/etablissement_form.js" %}"></script>
{% endblock %}

echo/templates/core/fichier_form.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}


<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">

        <h5 class="modal-title"> Déplacer un fichier </h5>
        <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
            <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
            <span class="svg-icon svg-icon-1">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1"
                                          transform="rotate(-45 6 17.3137)" fill="currentColor"/>
									<rect x="7.41422" y="6" width="16" height="2" rx="1"
                                          transform="rotate(45 7.41422 6)" fill="currentColor"/>
								</svg>
							</span>
            <!--end::Svg Icon-->
        </div>
    </div>

    <div class="modal-body">
        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Destination</label>
            <div class="col-lg-9 col-xl-6">
                <select name="dossier_fichier_patient" class="form-control form-control-lg ">
                    {% for dossier in dossier_patient %}
                        <option name="{{ dossier.nom }}" value="{{ dossier.id }}">
                            {{ dossier.nom }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>

    <div class="modal-footer p-2">
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
        <button type="submit" class="submit-btn btn btn-primary">Déplacer</button>
    </div>
</form>




echo/templates/core/list_header.html
<div class="subheader py-2 py-lg-4 subheader-solid mb-0" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Details-->
        <div class="d-flex align-items-center flex-wrap mr-2">
            <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">{{ module }}</h5>
        </div>
        <div class="d-flex align-items-center">
            <a href="{{ action_url }}" class="btn btn-primary font-weight-bold ml-2">
                <i class="ki ki-plus icon-sm"></i> {{ action_titre }}</a>
        </div>
    </div>
</div>

echo/templates/core/mesures_patient_form.html
{% extends "base_dialog.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block styles %}
    <style type="text/css">

    </style>
{% endblock %}
{% block content %}
    <form id="form_1" class="form" method="post" action="">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="card card-custom bg-white shadow-none">
            <div class="card-header fixed-header d-flex align-content-between align-items-center w-100 zindex-2 shadow-xs bg-light">
                <div class="card-title pl-2">
                    <h3 class="m-0">
                        {% if object %}
                            <h3 class="m-0 mt-1">{{ object.patient.titre }}</h3>
                        {% else %}
                            <h3 class="m-0 mt-1">{{ patient.titre }}</h3>
                        {% endif %}
                    </h3>
                </div>
                <div class="card-toolbar">
                    <button type="button" class="btn btn-default" onclick="window.parent.fermerModals()">Annuler
                    </button>
                    <button type="submit" id="btn_enregistrer" class="ml-2 btn btn-primary font-weight-bolder">
                        <i class="ki ki-check icon-sm"></i>
                        Enregistrer
                    </button>
                </div>
            </div>
            <div class="card-body px-0">
                <div class="py-4 px-4">
                    <div class="row">
                        <div class="form-group col-3">
                            <label>Tension</label>
                            {% render_field form.ta class+="form-control form-control-sm" %}
                        </div>
                        <div class="form-group col-3">
                            <label>Température</label>
                            {% render_field form.temperature class+="form-control form-control-sm" %}
                        </div>
                        <div class="form-group col-3">
                            <label>Poids</label>
                            {% render_field form.poids class+="form-control form-control-sm" %}
                        </div>
                        <div class="form-group col-3">
                            <label>Glycémie</label>
                            {% render_field form.gly class+="form-control form-control-sm" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

echo/templates/core/reglement_rapport.html
<div class="p-4">

    <form class="form mb-1">
        <div class="row">
            <div class="col-6 form-group">
                <div class='input-group' id='daterangepicker'>
                    <input type='text' class="form-control" readonly="readonly" id="date_range_input"
                           placeholder="intervalle de dates"/>
                    <div class="input-group-append">
															<span class="input-group-text">
																<i class="la la-calendar-check-o"></i>
															</span>
                    </div>
                </div>
            </div>
             <div class="col-6 form-group">
                <input placeholder="" data-col-index="4"
                       class="form-control form-control-sm" name="tags" type="text"
                       id="tags" value=""/>
            </div>
        </div>
        <div class="row">
             <div class="col-4 form-group">
              <label>Mutuelle</label>
                <select name="mutuelle" id="mutuelle" class="form-control form-control-sm"
                        data-col-index="5">
                    <option value="">Tous</option>
                    <option value="true">Oui</option>
                    <option value="false">Non</option>
                </select>

            </div>
            <div class="col-4 form-group">
                <label>Contenant une prestation</label>
                <select name="prestation" id="prestation" class="form-control form-control-sm"
                                                data-col-index="2" data-search-key="categorie">
                                            <option value="">---------</option>
                                            {% for prestation in prestations %}
                                                <option value="{{ prestation.prestation }}">{{ prestation.prestation }}</option>
                                            {% endfor %}
                                        </select>
            </div>
            <div class="col-4 form-group">
                <label>Nom du patient</label>
                <input type="text"
                       class="form-control form-control-sm datatable-input" placeholder=""
                       data-col-index="3"
                       value=""/>
            </div>

        </div>
        <div class="row">
            <div class="col-12">
                <button onclick="resetSearch()" class="btn btn-light-primary" type="button">
                    Réinitialiser
                </button>
            </div>
        </div>
    </form>
    <table class="table table-bordered table-checkable table-striped" id="datatable_rapport">
        <thead>
        <tr>
            <th>Date</th>
            <th>Montant Total</th>
            <th>Prestations</th>
            <th>Nom & Prénom patient</th>
            <th>mot clé</th>
            <th>mutuelle</th>
            <th>Action</th>
        </tr>
        </thead>
    </table>
</div>
<template id="actions-rapport-template">
    <a href="reglements/<%- id %>/modifier" class="btn btn-warning btn-icon btn-sm"
       title="Modifier">
        <i class="la la-edit icon-lg"></i>
    </a>
</template>



echo/templates/core/traitement_pma_form.html
{% extends "base_dialog.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="p-4">
        <form id="form_1" class="form" method="post" action="">
            {% csrf_token %}

            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            <div class="row">
                <div class="form-group col-5">
                    <label>{{ form.libelle.label }}</label>
                    {% render_field form.libelle class+="form-control form-control-sm" %}
                    <div class="invalid-feedback"
                         {% if form.libelle.errors %}style="display: block"{% endif %}>
                        {{ form.libelle.errors }}
                    </div>
                </div>
                <!--<div class="form-group col-4">
                    <label>{{ form.forme.label }}</label>
                    {% render_field form.forme class+="form-control form-control-sm" %}
                    <div class="invalid-feedback"
                         {% if form.forme.errors %}style="display: block"{% endif %}>
                        {{ form.forme.errors }}
                    </div>
                </div>-->
            </div>

            <!--<div class="row">
                <div class="form-group col-12">
                    <label>Posologie</label>
                    <textarea name="text" id="id_text" class="h-300px">
                        {% if object %}
                            {{ object.text|safe }}
                        {% else %}

                        {% endif %}
                    </textarea>
                    <div class="invalid-feedback"
                         {% if form.text.errors %}style="display: block"{% endif %}>
                        {{ form.text.errors }}
                    </div>
                </div>
            </div>-->

            <div class="d-flex mt-4 justify-content-end">
                <a href="/traitements-pma/" class="btn btn-default">Annuler</a>
                <button type="submit" id="btn_enregistrer" class="ml-2 btn btn-primary font-weight-bolder"
                        onclick="this.disabled=true,this.form.submit();">
                    <i class="ki ki-check icon-sm"></i>
                    Enregistrer
                </button>
            </div>

        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static "plugins/custom/tinymce/tinymce.bundle.js" %}"></script>
    <script type="text/javascript">

    </script>
    <script src="{% static "js/core/traitement_pma_form.js" %}"></script>
{% endblock %}